# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e4b0d62126e462a28d38c81ef0aa2f80ab5e6631efd68c027c13633dec3e8765d7718b1cf13ffaefa0f65d9f59fb64754ba9f1e117b75deb97ee575b2d7365

test:
  secret_key_base: 6f4eef7b5dd5b451deb1644552466d99d9510537991f2db220b1131d97456fdcc84bedeae0f34dcc0c5528af7887c9401c94834bc62890d4b33fb55b15cd2d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
